/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m2lformations;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Honoré
 */
public class Employe extends javax.swing.JFrame {

    BDD bdd = new BDD();
    Connection connexion;
    PreparedStatement reqPreparee;
    ResultSet resultat;

    /**
     * Creates new form Employe2
     */
    public Employe() {
        initComponents();
        ImageIcon icone = new ImageIcon("C:\\netbeans-workspace\\m2lformations\\resources\\images\\m2l.png");
        this.setIconImage(icone.getImage());
        try {
            connexion = bdd.gestionnaireDeConnexion();
            reqPreparee = connexion.prepareStatement("SELECT * FROM employe");
            resultat = reqPreparee.executeQuery();
            table.setModel(BDD.construireTable(resultat));
        } catch (SQLException ex) {
            Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitreEmploye = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        texteNom = new javax.swing.JTextField();
        textePrenom = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        texteEmail = new javax.swing.JTextField();
        labelMotpasse = new javax.swing.JLabel();
        texteMotpasse = new javax.swing.JTextField();
        boutonCreer = new javax.swing.JButton();
        boutonSupprimer = new javax.swing.JButton();
        labelStatut = new javax.swing.JLabel();
        comboStatut = new javax.swing.JComboBox<>();
        boutonModifier = new javax.swing.JButton();
        ScrollPaneEmploye = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M2L Formations");

        labelTitreEmploye.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitreEmploye.setText("Les employés de l'association");

        labelId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNom.setText("Le nom : ");

        labelPrenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPrenom.setText("Le prénom : ");

        texteNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textePrenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEmail.setText("L'email : ");

        texteEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelMotpasse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelMotpasse.setText("Le mot de passe : ");

        texteMotpasse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        boutonCreer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boutonCreer.setText("Créer");
        boutonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCreerActionPerformed(evt);
            }
        });

        boutonSupprimer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boutonSupprimer.setText("Supprimer");
        boutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSupprimerActionPerformed(evt);
            }
        });

        labelStatut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStatut.setText("Le statut : ");

        comboStatut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboStatut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        boutonModifier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boutonModifier.setText("Modifier");
        boutonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModifierActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        ScrollPaneEmploye.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTitreEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(ScrollPaneEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boutonCreer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(boutonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texteNom, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(texteEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMotpasse, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textePrenom)
                    .addComponent(texteMotpasse)
                    .addComponent(comboStatut, 0, 154, Short.MAX_VALUE)
                    .addComponent(boutonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTitreEmploye)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texteMotpasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMotpasse)
                            .addComponent(labelEmail)
                            .addComponent(texteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStatut)
                            .addComponent(comboStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boutonSupprimer)
                            .addComponent(boutonCreer)
                            .addComponent(boutonModifier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScrollPaneEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNom)
                            .addComponent(texteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrenom))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int ligne = table.getSelectedRow();
        labelId.setText(table.getValueAt(ligne, 0).toString());
        texteNom.setText(table.getValueAt(ligne, 1).toString());
        textePrenom.setText(table.getValueAt(ligne, 2).toString());
        texteEmail.setText(table.getValueAt(ligne, 3).toString());
        texteMotpasse.setText(table.getValueAt(ligne, 4).toString());
        comboStatut.setSelectedItem(table.getValueAt(ligne, 5).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void boutonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCreerActionPerformed
        // TODO add your handling code here:
        try {
            connexion = bdd.gestionnaireDeConnexion();
            reqPreparee = connexion.prepareStatement("INSERT INTO employe (nom, prenom, email, motpasse, statut) VALUES ('"
                    + texteNom.getText() + "','" + textePrenom.getText() + "','" + texteEmail.getText() + "','"
                    + texteMotpasse.getText() + "'," + comboStatut.getSelectedItem() + ")");
            int resultatinsert = reqPreparee.executeUpdate();
            if (resultatinsert != 0) {
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                JOptionPane.showMessageDialog(null, "L'employé a été crée", "Evènement crée",
                        JOptionPane.INFORMATION_MESSAGE);
                table.removeAll();
                reqPreparee = connexion.prepareStatement("SELECT * FROM employe");
                resultat = reqPreparee.executeQuery();
                table.setModel(BDD.construireTable(resultat));
            } else {
                JOptionPane.showMessageDialog(null, "L'employé n'a pas été crée", "Evènement non crée",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_boutonCreerActionPerformed

    private void boutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSupprimerActionPerformed
        // TODO add your handling code here:
        try {
            connexion = bdd.gestionnaireDeConnexion();
            reqPreparee = connexion.prepareStatement("DELETE FROM employe WHERE id='" + labelId.getText() + "'");
            int resultatsuppr = reqPreparee.executeUpdate();
            if (resultatsuppr != 0) {
                JOptionPane.showMessageDialog(boutonSupprimer, "L'employé a été supprimé", "Evénement supprimé",
                        JOptionPane.INFORMATION_MESSAGE);
                table.removeAll();
                reqPreparee = connexion.prepareStatement("SELECT * FROM employe");
                resultat = reqPreparee.executeQuery();
                table.setModel(BDD.construireTable(resultat));
            } else {
                JOptionPane.showMessageDialog(boutonSupprimer, "L'employé n'a pas été supprimé", "Evènement non supprimé",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_boutonSupprimerActionPerformed

    private void boutonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModifierActionPerformed
        // TODO add your handling code here:
        try {
            connexion = bdd.gestionnaireDeConnexion();
            reqPreparee = connexion.prepareStatement("UPDATE employe SET nom='" + texteNom.getText() + "',prenom='" + textePrenom.getText() + "', email='" + texteEmail.getText() + "', motpasse='" + texteMotpasse.getText() + "', statut='" + comboStatut.getSelectedItem() + "' WHERE id='" + labelId.getText() + "'");
            int resultatedite = reqPreparee.executeUpdate();
            if (resultatedite != 0) {
                JOptionPane.showMessageDialog(boutonModifier, "L'employé a été modifié", "Evènement modifié",
                        JOptionPane.INFORMATION_MESSAGE);
                table.removeAll();
                reqPreparee = connexion.prepareStatement("SELECT * FROM employe");
                resultat = reqPreparee.executeQuery();
                table.setModel(BDD.construireTable(resultat));
            } else {
                JOptionPane.showMessageDialog(boutonModifier, "L'employé n'a pas été modifié", "Evènement non modifié",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_boutonModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employe employe = new Employe();
                employe.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneEmploye;
    private javax.swing.JButton boutonCreer;
    private javax.swing.JButton boutonModifier;
    private javax.swing.JButton boutonSupprimer;
    private javax.swing.JComboBox<String> comboStatut;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelMotpasse;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JLabel labelStatut;
    private javax.swing.JLabel labelTitreEmploye;
    private javax.swing.JTable table;
    private javax.swing.JTextField texteEmail;
    private javax.swing.JTextField texteMotpasse;
    private javax.swing.JTextField texteNom;
    private javax.swing.JTextField textePrenom;
    // End of variables declaration//GEN-END:variables
}
