/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m2lformations;

import javax.swing.ImageIcon;

/**
 *
 * @author Honoré
 */
public class Menus extends javax.swing.JFrame {

    /**
     * Creates new form Menus2
     */
    public Menus() {
        initComponents();
        ImageIcon icone = new ImageIcon("C:\\netbeans-workspace\\m2lformations\\resources\\images\\m2l.png");
        this.setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitreMenus = new javax.swing.JLabel();
        boutonEmployes = new javax.swing.JButton();
        boutonFormations = new javax.swing.JButton();
        boutonSalles = new javax.swing.JButton();
        boutonIntervenants = new javax.swing.JButton();
        boutonDurees = new javax.swing.JButton();
        boutonPrestataires = new javax.swing.JButton();
        boutonSessions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M2L Formations");

        labelTitreMenus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitreMenus.setText("Veuillez choisir votre section");

        boutonEmployes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonEmployes.setText("Employés");
        boutonEmployes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEmployesActionPerformed(evt);
            }
        });

        boutonFormations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonFormations.setText("Formations");
        boutonFormations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonFormationsActionPerformed(evt);
            }
        });

        boutonSalles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonSalles.setText("Salles");
        boutonSalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSallesActionPerformed(evt);
            }
        });

        boutonIntervenants.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonIntervenants.setText("Intervenants");
        boutonIntervenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonIntervenantsActionPerformed(evt);
            }
        });

        boutonDurees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonDurees.setText("Durées");
        boutonDurees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDureesActionPerformed(evt);
            }
        });

        boutonPrestataires.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonPrestataires.setText("Prestataires");
        boutonPrestataires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonPrestatairesActionPerformed(evt);
            }
        });

        boutonSessions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutonSessions.setText("Sessions");
        boutonSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSessionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boutonEmployes, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(boutonDurees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boutonIntervenants, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonFormations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonSalles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonPrestataires, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTitreMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boutonSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitreMenus)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonEmployes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonFormations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonDurees)
                    .addComponent(boutonSalles))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonIntervenants)
                    .addComponent(boutonPrestataires))
                .addGap(26, 26, 26)
                .addComponent(boutonSessions)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonEmployesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEmployesActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonEmployes) {
            Employe employe = new Employe();
            employe.setVisible(true);
        }
    }//GEN-LAST:event_boutonEmployesActionPerformed

    private void boutonFormationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonFormationsActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonFormations) {
            Formation formation = new Formation();
            formation.setVisible(true);
        }
    }//GEN-LAST:event_boutonFormationsActionPerformed

    private void boutonDureesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDureesActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonDurees) {
            Duree duree = new Duree();
            duree.setVisible(true);
        }
    }//GEN-LAST:event_boutonDureesActionPerformed

    private void boutonSallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSallesActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonSalles) {
            Salle salle = new Salle();
            salle.setVisible(true);
        }
    }//GEN-LAST:event_boutonSallesActionPerformed

    private void boutonIntervenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonIntervenantsActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonIntervenants) {
            Intervenant intervenant = new Intervenant();
            intervenant.setVisible(true);
        }
    }//GEN-LAST:event_boutonIntervenantsActionPerformed

    private void boutonPrestatairesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonPrestatairesActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonPrestataires) {
            Prestataire prestataire = new Prestataire();
            prestataire.setVisible(true);
        }
    }//GEN-LAST:event_boutonPrestatairesActionPerformed

    private void boutonSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSessionsActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == boutonSessions) {
            Session session = new Session();
            session.setVisible(true);
        }
    }//GEN-LAST:event_boutonSessionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonDurees;
    private javax.swing.JButton boutonEmployes;
    private javax.swing.JButton boutonFormations;
    private javax.swing.JButton boutonIntervenants;
    private javax.swing.JButton boutonPrestataires;
    private javax.swing.JButton boutonSalles;
    private javax.swing.JButton boutonSessions;
    private javax.swing.JLabel labelTitreMenus;
    // End of variables declaration//GEN-END:variables
}
